all: 
	$(CC) $(CCFLAGS) $(INCLUDES) -c search.cpp -o $(OUTDIR)/search.o
	$(CC) $(CCFLAGS) $(INCLUDES) -c tt.cpp -o $(OUTDIR)/transposition.o
	$(CC) $(CCFLAGS) $(INCLUDES) -c evaluate.cpp -o $(OUTDIR)/eval.o
	$(CC) $(CCFLAGS) $(INCLUDES) -c movepicker.cpp -o $(OUTDIR)/movepicker.o