all: 
	$(CC) $(CCFLAGS) -I$(INCLUDE) -c search.cpp -o $(OUTDIR)/search.o
	$(CC) $(CCFLAGS) -I$(INCLUDE) -c tt.cpp -o $(OUTDIR)/transposition.o
	$(CC) $(CCFLAGS) -I$(INCLUDE) -c evaluate.cpp -o $(OUTDIR)/eval.o