all: 
	$(CC) $(CCFLAGS) -I$(INCLUDE) -c position.cpp -o $(OUTDIR)/position.o
	$(CC) $(CCFLAGS) -I$(INCLUDE) -c tables.cpp -o $(OUTDIR)/tables.o
	$(CC) $(CCFLAGS) -I$(INCLUDE) -c types.cpp -o $(OUTDIR)/types.o