all: 
	$(CC) $(CCFLAGS) $(INCLUDES) -c position.cpp -o $(OUTDIR)/position.o
	$(CC) $(CCFLAGS) $(INCLUDES) -c tables.cpp -o $(OUTDIR)/tables.o
	$(CC) $(CCFLAGS) $(INCLUDES) -c types.cpp -o $(OUTDIR)/types.o