all: 
	$(CC) $(CCFLAGS) $(INCLUDES) -c engine.cpp -o $(OUTDIR)/engine.o
	$(CC) $(CCFLAGS) $(INCLUDES) -c main.cpp -o $(OUTDIR)/entry.o
	$(CC) $(CCFLAGS) $(INCLUDES) -c log.cpp -o $(OUTDIR)/log.o
	$(CC) $(CCFLAGS) $(INCLUDES) -c misc.cpp -o $(OUTDIR)/misc.o