all: 
	$(CC) $(CCFLAGS) -I$(INCLUDE) -c engine.cpp -o $(OUTDIR)/engine.o
	$(CC) $(CCFLAGS) -I$(INCLUDE) -c main.cpp -o $(OUTDIR)/entry.o
	$(CC) $(CCFLAGS) -I$(INCLUDE) -c log.cpp -o $(OUTDIR)/log.o
	$(CC) $(CCFLAGS) -I$(INCLUDE) -c misc.cpp -o $(OUTDIR)/misc.o